In [5]:
def list_benefits():
    return "More organized code", "More readable code", "Easier code reuse", "Allowing programmers to share and connect code together"

def build_sentence(info):
    return "%s is a benefit of functions!" % info

def name_the_benefits_of_functions():
    list_of_benefits = list_benefits()
    for info in list_of_benefits:
        print(build_sentence(info))

In [6]:
name_the_benefits_of_functions()

More organized code is a benefit of functions!
More readable code is a benefit of functions!
Easier code reuse is a benefit of functions!
Allowing programmers to share and connect code together is a benefit of functions!


In [7]:
class MyClass:
    variable = "blah"

    def function(self):
        print("this is a message inside the class")

In [8]:
myobjectx = MyClass()
myobjectx.variable

'blah'

In [9]:
myobjectx = MyClass()
print(myobjectx.variable)

blah


In [10]:
myobjectx = MyClass()
myobjectx.function()

this is a message inside the class


In [11]:
class NumberHolder:

    def __init__(self, number):
        self.number = number

    def returnNumber(self):
        return self.number

In [12]:
var = NumberHolder(7)
print(var.returnNumber())

7


In [13]:
class Vehicle:
    name = ""
    kind = "car"
    color = "" 
    value = 100.00

    def description(self):
        desc_str = "%s is a %s %s worth $%.2f." % (self.name, self.color, self.kind, self.value)
        return desc_str

In [21]:
car1 = Vehicle()
car1.name = "Fer"
car1.color = "red"
car1.kind = "convertible" 
car1.value = 60000

car2 = Vehicle()
car2.name = "Jump"
car2.color = "blue"
car2.kind = "van" 
car2.value = 10000

In [22]:
print(car1.description())
print(car2.description())

Fer is a red convertible worth $60000.00.
Jump is a blue van worth $10000.00.


In [34]:
phonebook = {
    "John" : 938477566,
    "Jack" : 938377264,
    "Jill" : 947662781
}

In [35]:
for name, number in phonebook.items():
    print("Phone number of %s is %d" %(name, number))

Phone number of John is 938477566
Phone number of Jack is 938377264
Phone number of Jill is 947662781


In [36]:
phonebook.pop("Jill")
phonebook.update({"Jill" : 397345928})

In [33]:
phonebook.pop("Jill")
phonebook.add({"Jake":95678483})

KeyError: 'Jill'

In [38]:
phonebook = {  
    "John" : 938477566,
    "Jack" : 938377264,
    "Jill" : 947662781
}  

phonebook.pop("Jill")
phonebook["Jake"] = 31387419

if "Jake" in phonebook:  
    print("Jake is listed in the phonebook.")
    
if "Jill" not in phonebook:      
    print("Jill is not listed in the phonebook.")

Jake is listed in the phonebook.
Jill is not listed in the phonebook.


In [39]:
import re

find_members = []

for member in dir(re):
    if "find" in member:
        find_members.append(member)

print(sorted(find_members))

['findall', 'finditer']


In [40]:
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

In [41]:
import numpy as np

np_height = np.array(height)
np_weight = np.array(weight)

print(type(np_height))

<class 'numpy.ndarray'>


In [43]:
bmi = np_weight / np_height ** 2
print(bmi)

[23.34925219 27.88755755 28.75558507 25.48723993 23.87257618 25.84368152]


In [44]:
bmi > 23
bmi[bmi > 23]

array([23.34925219, 27.88755755, 28.75558507, 25.48723993, 23.87257618,
       25.84368152])

In [45]:
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

np_weight_kg = np.array(weight_kg)
np_weight_lb = np_weight_kg * 2.2

np_weight_lb

array([179.63 , 214.544, 209.55 , 204.556, 189.596, 194.59 ])

In [46]:
dict = {"country" : ["Brazil", "Russia", "India", "China", "South Africa"],
        "capital" : ["Brasilia", "Moscow", "New Dehli", "Beijing", "Pretoria"],
        "area" : [8.516, 17.10, 3.286, 9.597, 1.221],
        "population" : [200.4, 143.5, 1252, 1357, 52.98]}

import pandas as pd

brics = pd.DataFrame(dict)
print(brics)

        country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Dehli   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98


In [47]:
brics.index = ["BR", "RU", "IN", "CH", "SA"]
print(brics)

         country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Dehli   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98


In [48]:
import random

def lottery():
    for i in range(6):
        yield random.randint(1,40)
    yield random.randint(1,15)

for random_number in lottery():
    print("And the next number is... %d" %(random_number))

And the next number is... 16
And the next number is... 33
And the next number is... 1
And the next number is... 1
And the next number is... 14
And the next number is... 25
And the next number is... 11


In [49]:
a = 1
b = 2
a, b = b, a
print(a,b)

2 1


In [50]:
def fib():
    a, b = 1, 1
    while 1:
        yield a
        a, b = b, a + b

import types
if type(fib()) == types.GeneratorType:
    print("Good, The fib function is a generator.")

    counter = 0
    for n in fib():
        print(n)
        counter += 1
        if counter == 10:
            break

Good, The fib function is a generator.
1
1
2
3
5
8
13
21
34
55


In [57]:
numbers = [34.6, -203.4, 44.9, 68.3, -12.2, 44.6, 12.7]
newlist = [int(x) for x in numbers if x > 0]
print(newlist)

[34, 44, 68, 44, 12]


In [58]:
l = [2,4,7,3,14,19]
for i in l:
    my_lambda = lambda x : (x % 2) == 1
    print(my_lambda(i))

False
False
True
True
False
True


In [61]:
def foo(first, second, third, *therest):
    print("First: %s" %(first))
    print("Second: %s" %(second))
    print("Third: %s" %(third))
    print("And all the rest... %s" %(list(therest)))

foo(1,2,3,4,5,6)

First: 1
Second: 2
Third: 3
And all the rest... [4, 5, 6]


In [62]:
def bar(first, second, third, **options):
    if options.get("action") == "sum":
        print("The sum is: %d" %(first + second + third))
    if options.get("number") == "first":
        return first
result = bar(1,2,3, action = "sum", number = "first")
print("Result: %d" %(result))

The sum is: 6
Result: 1


In [67]:
def foo(a, b, c, *args):
    return len(args)

def bar(a, b, c, **kwargs):
    return kwargs["magicnumber"] == 7

# test code
if foo(1, 2, 3, 4) == 1:
    print("Good.")
if foo(1, 2, 3, 4, 5) == 2:
    print("Better.")
if bar(1, 2, 3, magicnumber=6) == False:
    print("Great.")
if bar(1, 2, 3, magicnumber=7) == True:
    print("Awesome!")

Good.
Better.
Great.
Awesome!


In [68]:
import re
pattern = re.compile(r"\[(on|off)\]") # Slight optimization
print(re.search(pattern, "Mono: Playback 65 [75%] [-16.50dB] [on]"))
# Returns a Match object!
print(re.search(pattern, "Nada...:-("))
# Doesn't return anything.
# End Example

# Exercise: make a regular expression that will match an email

def test_email(your_pattern):
    pattern = re.compile(your_pattern)
    emails = ["john@example.com", "python-list@python.org", "wha.t.`1an?ug{}ly@email.com"]
    for email in emails:
        if not re.match(pattern, email):
            print("You failed to match %s" % (email))
        elif not your_pattern:
            print("Forgot to enter a pattern!")
        else:
            print("Pass")
# Your pattern here!
pattern = r"\"?([-a-zA-Z0-9.`?{}]+@\w+\.\w+)\"?"
test_email(pattern)

<re.Match object; span=(35, 39), match='[on]'>
None
Pass
Pass
Pass
